<?PHP


$TPGBHS=
"(DESCRIPTION =
(ADDRESS = (PROTOCOL = TCP)(HOST = 100.100.1.11)(PORT = 1521))
(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = mbillsb)
)
)";
$conn = ocilogon( "TPGBHS", "TPGBHS",$TPGBHS,"WE8ISO8859P15");

?>